INSERT INTO [dbo].[Product] ([id], [title], [price], [small_image_url], [large_image_url], [description], [producer], [special]) VALUES (1, N'Lenovo IdeaPad G580 Dark Metal', 25000.00, N'~/Images/image2.jpg', N'~/Images/notebook_large.jpg', N'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', N'Lenovo', 1)

INSERT INTO [dbo].[Product] ([id], [title], [price], [small_image_url], [large_image_url], [description], [producer], [special]) VALUES (2, N'Toshiba Portégé Z930-14E', 17355.00, N'~/Images/image2.jpg', N'~/Images/notebook_large.jpg', N'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', N'Toshiba', 1)

INSERT INTO [dbo].[Product] ([id], [title], [price], [small_image_url], [large_image_url], [description], [producer], [special]) VALUES (3, N'Acer Aspire E1-531G černý', 9490.00, N'~/Images/image2.jpg', N'~/Images/notebook_large.jpg', N'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', N'Acer', 1)

INSERT INTO [dbo].[Product] ([id], [title], [price], [small_image_url], [large_image_url], [description], [producer], [special]) VALUES (4, N'Televizor Tesla, barevný', 999.99, NULL, NULL, N'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', N'Tesla', 1)

INSERT INTO [dbo].[Product] ([id], [title], [price], [small_image_url], [large_image_url], [description], [producer], [special]) VALUES (5, N'iPad 2 16GB Wi-Fi Black', 8256.00, N'~/Images/ipad_small.jpg', N'~/Images/ipad_large.jpg', N'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', N'Apple', 1)

INSERT INTO [dbo].[Product] ([id], [title], [price], [small_image_url], [large_image_url], [description], [producer], [special]) VALUES (6, N'Sony VAIO Duo 11 Touch', 24785.00, N'~/Images/image2.jpg', N'~/Images/notebook_large.jpg', N'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', N'Sony', 1)

INSERT INTO [dbo].[Product] ([id], [title], [price], [small_image_url], [large_image_url], [description], [producer], [special]) VALUES (7, N'iPad mini 64GB WiFi Black&Slate', 25612.00, N'~/Images/ipad_small.jpg', N'~/Images/ipad_large.jpg', N'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', N'Apple', 1)

INSERT INTO [dbo].[Product] ([id], [title], [price], [small_image_url], [large_image_url], [description], [producer], [special]) VALUES (8, N'MacBook Pro 15" CZ', 10742.00, N'~/Images/image2.jpg', N'~/Images/notebook_large.jpg', N'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', N'Apple', 1)

INSERT INTO [dbo].[Product] ([id], [title], [price], [small_image_url], [large_image_url], [description], [producer], [special]) VALUES (9, N'HP Pavilion g6-2252 Linen White', 13215.00, N'~/Images/image2.jpg', N'~/Images/notebook_large.jpg', N'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', N'HP', 1)

INSERT INTO [dbo].[Product] ([id], [title], [price], [small_image_url], [large_image_url], [description], [producer], [special]) VALUES (10, N'HP ProBook 4540s', 12388.00, N'~/Images/image2.jpg', N'~/Images/notebook_large.jpg', N'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', N'HP', 1)

INSERT INTO [dbo].[Product] ([id], [title], [price], [small_image_url], [large_image_url], [description], [producer], [special]) VALUES (11, N'HP ENVY dv7-7235ec Midnight Black', 21479.00, N'~/Images/image2.jpg', N'~/Images/notebook_large.jpg', N'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', N'HP', 1)

INSERT INTO [dbo].[Product] ([id], [title], [price], [small_image_url], [large_image_url], [description], [producer], [special]) VALUES (12, N'32" Sony Bravia KDL-32EX343', 7017.00, N'~/Images/lcdtv_small.jpg', N'~/Images/lcdtv_large.jpg', N'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', N'Samsung', 1)

INSERT INTO [dbo].[Product] ([id], [title], [price], [small_image_url], [large_image_url], [description], [producer], [special]) VALUES (13, N'Sony VAIO Pro 13', 28917.00, N'~/Images/image2.jpg', N'~/Images/notebook_large.jpg', N'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', N'Sony', 1)

INSERT INTO [dbo].[Product] ([id], [title], [price], [small_image_url], [large_image_url], [description], [producer], [special]) VALUES (14, N'MacBook Pro 13" CZ', 25612.00, N'~/Images/image2.jpg', N'~/Images/notebook_large.jpg', N'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', N'Apple', 1)

INSERT INTO [dbo].[Product] ([id], [title], [price], [small_image_url], [large_image_url], [description], [producer], [special]) VALUES (15, N'Sony Xperia Tablet Z, 16GB Wifi, černý', 10736.00, N'~/Images/android_small.jpg', N'~/Images/android_large.jpg', N'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', N'Sony', 1)

INSERT INTO [dbo].[Product] ([id], [title], [price], [small_image_url], [large_image_url], [description], [producer], [special]) VALUES (16, N'Samsung Galaxy Note 10.1 (N8010) Pearl Grey Wi-Fi', 9499.00, N'~/Images/android_small.jpg', N'~/Images/android_large.jpg', N'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', N'Samsung', 1)

INSERT INTO [dbo].[Product] ([id], [title], [price], [small_image_url], [large_image_url], [description], [producer], [special]) VALUES (17, N'40" Samsung UE40EH5000', 8264.00, N'~/Images/lcdtv_small.jpg', N'~/Images/lcdtv_large.jpg', N'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', N'Samsung', 1)