//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EshopMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Category = new HashSet<Category>();
            this.OrderProduct = new HashSet<OrderProduct>();
            this.CartProduct = new HashSet<CartProduct>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public decimal price { get; set; }
        public string small_image_url { get; set; }
        public string large_image_url { get; set; }
        public string description { get; set; }
        public string producer { get; set; }
        public bool special { get; set; }
    
        public virtual ICollection<Category> Category { get; set; }
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        public virtual ICollection<CartProduct> CartProduct { get; set; }
    }
}
