//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EshopMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public ShoppingCart()
        {
            this.CartProduct = new HashSet<CartProduct>();
        }
    
        public int Id { get; set; }
        public string UserId { get; set; }
    
        public virtual ICollection<CartProduct> CartProduct { get; set; }
    }
}
